### ISSUE TITLE
Trace_link throwing Key Error

### ISSUE THREAD

**Issue by cad-x2** [astra-sim/astra-sim#169]
# Execution Observer Records Orphan Childs with a gap in the ID

We are trying to replicate the entire workflow mentioned in your paper https://arxiv.org/pdf/2305.14516.pdf by the instructions in Chakra's wiki page (https://github.com/mlcommons/chakra/wiki/Chakra-Execution-Trace-Collection-%E2%80%90-A-Comprehensive-Guide-on-Merging-PyTorch-and-Kineto-Traces) by running llama2 finetuning locally and converting the collected traces into chakra traces. (using newest PyTorch Nightly, same steps as the llama recipies)

The issue is a discontinuous event ID in ET traces, eventaully leading to missing parents and eventual crash to the link for et_plus file, we were re-producing it in two different launch sequence, Direct Pytorch Profiler collection and ET Replay Tool.

### Using Both Execution Observer and Profiler (a.k.a. kinetto)

Sample Output of Execution Observer - ET Trace we collected:

```JSON
{
      "name": "aten::t", "id": 13154, "rf_id": 11175, "parent": 13153, "fw_parent": 0, "seq_id": 5532, "scope": 0, "tid": 3, "fw_tid": 0, "op_schema": "aten::t(Tensor(a) self) -> Tensor(a)",
      "inputs": [[12066,129,157286400,45088768,4,"cuda:0"]], "input_shapes": [[4096,11008]], "input_types": ["Tensor(float)"],
      "outputs": [[13140,129,157286400,45088768,4,"cuda:0"]], "output_shapes": [[11008,4096]], "output_types": ["Tensor(float)"]
},

### The Parent ID 13153 never reflected to a real event as we were never able to find one in the ET file. 
```
### Setup: We have tried various location to start the ET Observer using the convention:
For PyTorch ET Trace
```python
    from torch.profiler import profile, record_function, ProfilerActivity, schedule, tensorboard_trace_handler
    from torch.profiler import _ExperimentalConfig, ExecutionTraceObserver

    et = None
    et_file = f"{out_file_prefix}_et.json"
    et = ExecutionTraceObserver()
    et.register_callback(et_file)
    traceObjects['et'] = et
```
For PyTorch Profiler (a.k.a. Kinetto):
```python
# benchmark.py
        with torch.autograd.profiler.profile(
            enabled = True,
            use_cuda= False, # use_cuda 
            use_kineto=True,
            record_shapes=True,
            profile_memory=True,
            with_stack = True,
            with_flops = True,
            with_modules = True,
            experimental_config=cupti_profiler_config,
            # use_cpu enables profiling and recodring of CPU pytorch 
            # operators.
            # This is useful in CUPTI profiler mode if we are 
            # measuring per GPU kernel metrics.
            use_cpu=True #(not enabled_cupti) or True # args.
            cupti_profiler_measure_per_kernel,
        ) as prof:
## PyTorch Profiler As Alternative Attempt:
        with profile(
            activities = [ProfilerActivity.CPU, ProfilerActivity.CUDA],
            on_trace_ready  = trace_handler,
            profile_memory = True,
            schedule = tracing_schedule,
            record_shapes = False,
            with_stack = False
            ) as prof:
```
and tried the following methods:
```python
# 1 Start and Stop as a Wrapper:
    et.start()
    model.train(...)
    et.stop()

# 2 Start and Stop inside the Train utility:
/home/123/workspace/llama2/llama-recipes/src/llama_recipes/utils/train_utils.py

class model(..)
    def train(self, ...):
        et = None
        et_file = f"{out_file_prefix}_et.json"
        et = ExecutionTraceObserver()
        et.register_callback(et_file)
        traceObjects['et'] = et
        et.start()

        for epoch in dataloader...
        # The ML Code ...

        et.stop() # Either at the finish of a certain step, or at the end of Epoch
```
### Both Giving the following error (Kinetto Trace Collected via standard PyTorch Profiler, also attempted same convention in run_benchamrk.py)
```bash
python3 ./tools/trace_link.py --et-file /home/123/llama_trace/lion_1_25/12_42/1-25-dolphine/llama2_trace_1-25-dolphine_rank_0__et.json --kineto-file /home/ngip/carrick/llama_trace/lion_1_25/12_42/1-25-dolphine/llama2_trace_1-25-dolphine_rank_0_4.json --exact-match --annotation 'enumerate(DataLoader)#_MultiProcessingDataLoaderIter.__next__'
...
...
...
  File "/home/123/astra-sim/extern/graph_frontend/param/train/compute/python/./tools/trace_link.py", line 827, in dump_et_file
    node["parent"] = assigned_ids[node["parent"]]
KeyError: 13153
```
## Using ET_Replay from collected ET Traces resulted the same error. 
```bash

cd param/train/comms/pt
pip install .
cd ../../compute/python
pip install -r requirements.txt
python setup.py install
w-009:~/astra-sim/extern/graph_frontend/param/train/compute/python$ python3 -m tools.et_replay --input llama2_trace_1-24-lion_rank_0__et.json --warmup-iter 10 --iter 1 --compute --profile-replay
[2024-01-25 13:23:34,670] et_replay.py:132 [INFO]: FB internals not present
#Operators to execute:  2487
Tensor count with same identifier but different shapes:8, total tensor: 1774
Start to execution:
Finished one iteration.
Finished one iteration.
Finished one iteration.
Finished one iteration.
Finished one iteration.
Finished one iteration.
Finished one iteration.
Finished one iteration.
Finished one iteration.
Finished one iteration.
STAGE:2024-01-25 13:23:51 3359815:3359815 ActivityProfilerController.cpp:312] Completed Stage: Warm Up
Finished one iteration.
STAGE:2024-01-25 13:23:51 3359815:3359815 ActivityProfilerController.cpp:318] Completed Stage: Collection
STAGE:2024-01-25 13:23:51 3359815:3359815 ActivityProfilerController.cpp:322] Completed Stage: Post Processing
[2024-01-25 13:23:51,595] utility.py:30 [WARNING]: Chrome profile trace written to /tmp/tmp_20240125_799866c_3359815.json
Execution finished!
STAGE:2024-01-25 13:23:51 3359815:3359815 ActivityProfilerController.cpp:312] Completed Stage: Warm Up
STAGE:2024-01-25 13:23:51 3359815:3359815 ActivityProfilerController.cpp:318] Completed Stage: Collection
STAGE:2024-01-25 13:23:51 3359815:3359815 ActivityProfilerController.cpp:322] Completed Stage: Post Processing
Replay time per iteration: 227.18 ms
Operator coverage: 2487 / 2597 = 0.9576434347323836
[2024-01-25 13:23:51,604] et_replay.py:1454 [INFO]: FB internals not present

w-009:~/astra-sim/extern/graph_frontend/param/train/compute/python$ python3 ./tools/trace_link.py --et-file llama2_trace_1-24-lion_rank_0__et.json --kineto-file tmp_20240125_799866c_3359815.json --exact-match --annotation 'enumeraLoaderIter.__next__'
[2024-01-25 13:25:58,522] execution_trace.py:441 [INFO]: Iteration node ids list = [1, 20, 164683, 220631, 276171]
[2024-01-25 13:25:58,522] trace_link.py:294 [INFO]: Execution trace has 4 > 1 iterations.
[2024-01-25 13:25:58,522] execution_trace.py:682 [INFO]: Copying nodes for iter 2 for ids in the range [164683, 220631)
[2024-01-25 13:26:12,267] execution_trace.py:730 [INFO]: Nodes trimmed ET = 50390
[2024-01-25 13:26:12,273] trace_link.py:306 [INFO]: Number of original ops in execution trace: 12696
[2024-01-25 13:26:12,361] trace_link.py:225 [INFO]: Kineto trace has 0 segments
[2024-01-25 13:26:12,361] trace_link.py:338 [WARNING]: Could not find annotation enumerate(DataLoader)#_MultiProcessingDataLoaderIter.__next__ in kineto file using the whole file, processing could be very slow!!
[2024-01-25 13:26:12,361] trace_link.py:343 [INFO]: Number of original cpu ops in kineto trace: 7662
[2024-01-25 13:26:12,361] trace_link.py:344 [INFO]: Number of original gpu ops in kineto trace: 366
[2024-01-25 13:26:12,361] trace_link.py:350 [INFO]: Average iteration latency: 227302.0
[2024-01-25 13:26:13,031] trace_link.py:588 [INFO]: Ops count mismatch between kineto and execution trace ( et size = 12696, kineto size: 7664 )
Traceback (most recent call last):
  File "./tools/trace_link.py", line 895, in <module>
    main()  # pragma: no cover
  File "./tools/trace_link.py", line 884, in main
    dump_et_file(
  File "./tools/trace_link.py", line 822, in dump_et_file
    node["parent"] = assigned_ids[node["parent"]]
KeyError: 74174
```

## The Newest Refactor On tracelink.py (https://github.com/facebookresearch/param/blob/ffb533d3d6e26823fb5e9fa7f8f32419d3851ca5/train/compute/python/tools/trace_link.py) also run into an issue:
```bash
PyTorch and Kineto traces.
[2024-01-26 12:03:55,977] trace_link.py:513 [INFO]: Adding process annotation op with name [pytorch|profiler|execution_trace|process] and ts 1706288564709901
[2024-01-26 12:03:55,977] trace_link.py:535 [INFO]: Adding thread annotation op for tid 27019 with name [pytorch|profiler|execution_trace|thread] and ts 1706288564709901
[2024-01-26 12:03:55,977] trace_link.py:553 [INFO]: Mapping PyTorch ET nodes to Kineto operators.
[2024-01-26 12:03:56,035] trace_link.py:559 [ERROR]: Mismatch in operator count between PyTorch and Kineto traces.
Traceback (most recent call last):
  File "./tools/trace_link.py", line 892, in <module>
    main()
  File "./tools/trace_link.py", line 887, in main
    linker.link_traces()
  File "./tools/trace_link.py", line 455, in link_traces
    self.exact_match()
  File "./tools/trace_link.py", line 471, in exact_match
    self.map_pytorch_to_kineto_ops()
  File "./tools/trace_link.py", line 560, in map_pytorch_to_kineto_ops
    raise RuntimeError(error_msg)
RuntimeError: Mismatch in operator count between PyTorch and Kineto traces.
```
 We generated the Kinetto Files from et replay with 
 ```bash
 python3 ./tools/et_replay.py --input llama2_trace_1-26-white-whale_rank_0_140194822305600_11069_et.json  --warmup-iter 1 --iter 1 --compute --
profile-replay
 ```

**Comment by cad-x2** [comment]
Things

**Comment by dageita** [comment]
How to generate such as xxx_0_eg.json, xxx_1_eg.json, xxx_2_eg.json files when trained by multiple gpus?
