### ISSUE TITLE
我在尝试et_converter转换时，出现了问题

### ISSUE THREAD

**Issue by 32HD** [astra-sim/astra-sim#214]
root@145605beb0f5:/app/astra-sim/extern/graph_frontend/chakra# python3 -m chakra.et_converter.et_converter     --input_type Text     --input_filename ../../../inputs/workload/ASTRA-sim-1.0/Resnet50_DataParallel.txt     --output_filename ../../../inputs/workload/ASTRA-sim-2.0/Resnet50_DataParallel     --num_npus 64     --num_dims 1     --num_passes 1
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/et_converter.py", line 9, in <module>
    from .text2chakra_converter import Text2ChakraConverter
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/text2chakra_converter.py", line 8, in <module>
    from chakra.et_def.et_def_pb2 import (
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_def/et_def_pb2.py", line 9, in <module>
    from google.protobuf import runtime_version as _runtime_version
ImportError: cannot import name 'runtime_version' from 'google.protobuf' (/usr/local/lib/python3.8/dist-packages/google/protobuf/__init__.py)
root@145605beb0f5:/app/astra-sim/extern/graph_frontend/chakra#

**Comment by 32HD** [comment]
我通过将protobuf更新到了5.x.x解决了这个问题，希望大家不用被这个错误困扰（😭）

**Comment by Cioccoo** [comment]
Hi @32HD, may I know which version of Chakra you are using? And are you able to get valid output now?

**Comment by 32HD** [comment]
> Hi @32HD, may I know which version of Chakra you are using? And are you able to get valid output now?
@Cioccoo ,hi, I use Chakra0.0.4, and I can run simple example normally. I'm trying to run megatron-lm in astra, but i can't get any output. Do you know how to get DAG from trace?

**Comment by 32HD** [comment]
<img width="788" alt="截屏2024-09-10 09 54 18" src="https://github.com/user-attachments/assets/1f3ad74f-185a-4278-9e0b-fc952f7d3be5">

**Comment by buuunyuun** [comment]
这样子的话是ns3编译失败了吗😭@32HD 怎么解决嘞

**Comment by 32HD** [comment]
> 这样子的话是ns3编译失败了吗😭@32HD 怎么解决嘞



> 这样子的话是ns3编译失败了吗😭@32HD 怎么解决嘞

具体的问题是？没懂你的意思

**Comment by Swan331** [comment]
你好！我这里显示缺失这个模块。你有没有遇到这个问题咧
![b56eec03f681cd15eadef25beba75f4](https://github.com/user-attachments/assets/379c4dbf-d0a3-4315-819c-26b4a7ee9c20)

**Comment by tninth** [comment]
> <img alt="截屏2024-09-10 09 54 18" width="788" src="https://private-user-images.githubusercontent.com/64127766/365863794-1f3ad74f-185a-4278-9e0b-fc952f7d3be5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNzA0MTEsIm5iZiI6MTczNTI3MDExMSwicGF0aCI6Ii82NDEyNzc2Ni8zNjU4NjM3OTQtMWYzYWQ3NGYtMTg1YS00Mjc4LTllMGItZmM5NTJmN2QzYmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAzMjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlN2I3YThlNzIxN2NmODc4Y2IwNjQ3ODkxNGE2ZTgwNTg5OTJmNDM1MmNiNjRlZWQzMTRmYmNlMzQ3MjA2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.su600rQdmh5wklL95xRUTpUagRTwRnxIUJJNoONRaY0"> ，也许你需要关注 Chakra wiki 而不是 astrasim， （https://github.com/mlcommons/chakra/wiki/Chakra-Execution-Trace-Collection-%E2%80%90-A-Comprehensive-Guide-on-Merging-PyTorch-and-Kineto-Traces）

Hello,when i was running this(./build/astra-ns3/build.sh -r) ,i found that in the build.sh ,Config files for SYSTEM, MEMORY, and LOGICAL_TOPOLOGY have been moved  but the path in the build script hasn't been updated,although i have updated them ,i still couldn't find the "WORKLOAD="${SCRIPT_DIR:?}"/../../extern/graph_frontend/chakra/one_comm_coll_node_allgather"  ,can i ask how you run it,thanks
